export const ADD_ITEM = 'ADD_ITEM';
export const ADD_FAVOURITES = 'ADD_FAVOURITES';
export const FETCHED_USERS = 'FETCHED_USERS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const RESET_CURRENT_USER = 'RESET_CURRENT_USER';
